import "@/app/globals.css"; // Estilos globales

import {
  geistMono,
  geistSans,
  anton,
  bebasNeue,
  archivoBlack,
  spaceGrotesk,
  oswald,
  leagueSpartan,
  barlowCondensed,
  archivoNarrow,
  teko,
} from "@/fonts/fonts";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      {/* // <html lang="es" suppressHydrationWarning> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${spaceGrotesk.variable} ${anton.variable} ${archivoBlack.variable}
        ${oswald.variable}
        ${leagueSpartan.variable}
        ${barlowCondensed.variable}
        ${archivoNarrow.variable}
        ${teko.variable}
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
